server:
#  port: 8888
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.2:3306/user_data?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3306/user_data?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
#    bootstrap-servers: localhost:9092
    bootstrap-servers: 172.19.0.2:9092
    producer:
      properties:
        spring:
          json:
            trusted.packages: "*"
            use.type.headers: false
#            type.mapping: "User:winitech.practice.system.domain.user.domain.User"

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR

message:
  topic:
    create: user_create
    update: user_update
    delete: user_delete