server:
#  port: 8081
  port: 8080

spring:
  application:
    name: backup
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.4:3306/user_backup?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3307/user_backup?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
#    bootstrap-servers: localhost:9092
    bootstrap-servers: 172.19.0.2:9092
    template:
      default-topic: test
    consumer:
      auto-offset-reset: earliest
      group-id: testgroup
      properties:
        spring:
          json:
            trusted.packages: "*"
            use.type.headers: false
#            type.mapping: "UserData:winitech.practice.backup.userdata.domain.UserData"

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR

message:
  topic:
    create: user_create
    update: user_update
    delete: user_delete